name: docker_build

on: [push]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: docker-airflow
  REGISTRY_HOSTNAME: asia.gcr.io
  AIRFLOW_VERSION: 1.10.10

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/docker-airflow:${GITHUB_SHA::7} .
      - name: Push the docker image
        run: |
          export TAG=`echo ${GITHUB_SHA::7}`
          echo $TAG
          docker push "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":"$TAG"
          docker tag "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":latest
          docker push "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":latest
          docker tag "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":"$TAG" "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":"$AIRFLOW_VERSION"
          docker push "$REGISTRY_HOSTNAME"/"${{ secrets.GCP_PROJECT_ID }}"/"$IMAGE":"$AIRFLOW_VERSION"
